server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/student?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    max-active: 20
    min-idle: 1
    initial-size: 2
  jpa:
    hibernate:
      ddl-auto: create #create: if exists, drop it; update/validate
    show-sql: true
  mvc:
    static-path-pattern: /**

mybatis:
  type-aliases-package: com.jeizas.entity