server:
  port: 8081
spring:

  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    max-active: 20
    min-idle: 1
    initial-size: 2
    hikari:
          maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
          maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  jpa:
    hibernate:
      ddl-auto: create #create: if exists, drop it; update/validate
    show-sql: true
  mvc:
    static-path-pattern: /**

mybatis:
  type-aliases-package: com.jeizas.entity

---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8

---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/student?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8